# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180115_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
