# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20180115_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateField(),
        ),
    ]
